# Generated by Django 4.2.2 on 2023-10-24 02:01

import FriendFunctionality.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FriendFunctionality', '0001_initial'),
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='request_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_target', to='UserManagement.solutionuserprofile', validators=[FriendFunctionality.models.validate_requesttarget]),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requesting_user', to='UserManagement.solutionuserprofile'),
        ),
        migrations.AddField(
            model_name='friendlist',
            name='friends_list',
            field=models.ManyToManyField(blank=True, related_name='all_friends', to='UserManagement.solutionuserprofile', verbose_name='friend_list_set'),
        ),
        migrations.AddField(
            model_name='friendlist',
            name='owner_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='friend_record_owner', to='UserManagement.solutionuserprofile', verbose_name='friendlist_owner'),
        ),
        migrations.AddConstraint(
            model_name='friendrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('request_state', False)), fields=('requester', 'request_target'), name='unique_freind_request'),
        ),
    ]
