# Generated by Django 4.2.2 on 2023-11-14 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FriendList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_state', models.BooleanField(default=False)),
                ('request_datetime', models.DateTimeField(auto_now_add=True)),
                ('request_response', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
