# Generated by Django 4.2.2 on 2023-07-12 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dictionaryCore', models.CharField(blank=True, max_length=500, null=True)),
                ('dictionaryRelated', models.CharField(blank=True, max_length=1500, null=True)),
                ('requirements', models.BinaryField(default=0, max_length=1)),
                ('minimum_words', models.IntegerField(default=3)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Connected_Owner')),
            ],
            options={
                'verbose_name': 'passwordgenerators',
                'verbose_name_plural': 'passwordgenerators',
            },
        ),
    ]
