# Generated by Django 4.2.2 on 2023-07-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PasswordGenerator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordgeneration',
            name='dictionaryCore',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='passwordgeneration',
            name='dictionaryRelated',
            field=models.CharField(blank=True, default='', max_length=1500, null=True),
        ),
    ]
