# Generated by Django 4.2.2 on 2023-07-12 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PasswordGenerator', '0002_alter_passwordgeneration_dictionarycore_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordgeneration',
            name='requirements',
        ),
    ]
