# Generated by Django 4.2.2 on 2023-07-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PasswordGenerator', '0003_remove_passwordgeneration_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordgeneration',
            name='minimum_numbers',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='passwordgeneration',
            name='minimum_special_characters',
            field=models.IntegerField(default=3),
        ),
    ]
