# Generated by Django 4.2.2 on 2023-10-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_provider', models.CharField(blank=True, default='Undefined', max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(default='Uninitialized', max_length=50)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('service_type', models.CharField(blank=True, choices=[('Public', 'shared'), ('Private', 'unshared')], default=('Public', 'shared'), max_length=50)),
                ('added_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
