# Generated by Django 4.2.2 on 2023-11-24 01:33

import CredentialVault.models
from django.db import migrations, models
import encrypted_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_service_provider', encrypted_fields.fields.EncryptedCharField(blank=True, default='Undefined', max_length=50)),
                ('service_provider', encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_service_provider', hash_key=CredentialVault.models.get_user_key, max_length=66, null=True)),
                ('_username', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=100)),
                ('username', encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_username', hash_key=CredentialVault.models.get_user_key, max_length=66, null=True)),
                ('_password', encrypted_fields.fields.EncryptedCharField(default='', max_length=100)),
                ('password', encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_password', hash_key=CredentialVault.models.get_user_key, max_length=66, null=True)),
                ('_email', encrypted_fields.fields.EncryptedEmailField(blank=True, default='', max_length=254)),
                ('email', encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_email', hash_key=CredentialVault.models.get_user_key, max_length=66, null=True)),
                ('service_type', models.CharField(blank=True, choices=[('Public', 'shared'), ('Private', 'private')], default=('Public', 'shared'), max_length=50)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('_access_granted_to', encrypted_fields.fields.EncryptedTextField(blank=True, default='', max_length=200, null=True)),
                ('access_granted_to', encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_access_granted_to', hash_key=CredentialVault.models.get_user_key, max_length=66, null=True)),
                ('requesting_access', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.IntegerField(choices=[('CredentialAccessRequest', 0), ('CredentialAccessDenail', 1), ('CredentialAccessAccepted', 2), ('CredentialChangeRequired', 3), ('CredentialChangeCompleted', 4), ('CredentialRecordAdded', 5), ('CredentialRecordRemoved', 6), ('CredentialRecordModified', 7), ('CredentialRecordAccessed', 8), ('CredentialAccessRequested', 9)])),
                ('description', models.TextField(default='', max_length=500)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(choices=[('active', 0), ('inactive', 1), ('silenced', 2)], default=True)),
                ('urgency', models.BooleanField(default=False)),
                ('other_user', models.CharField(default=None, max_length=100, null=True, verbose_name='requesting_user')),
                ('read', models.BooleanField(default=False)),
            ],
        ),
    ]
