# Generated by Django 4.2.2 on 2023-07-12 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, default='Undefined', max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(default='Uninitialized', max_length=50)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('service_type', models.CharField(blank=True, choices=[('UNDEFINED', 'undefined'), ('BUSINESS', 'business'), ('CUSTOM', 'custom')], default=('UNDEFINED', 'undefined'), max_length=50)),
                ('shares', models.CharField(blank=True, max_length=10000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.AddConstraint(
            model_name='credentials',
            constraint=models.UniqueConstraint(fields=('service', 'username', 'owner'), name='unique_service_username_owner'),
        ),
    ]
