# Generated by Django 4.2.2 on 2023-11-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CredentialVault', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='purpose',
            field=models.IntegerField(choices=[('CredentialAccessRequest', 0), ('CredentialAccessDenail', 1), ('CredentialAccessAccepted', 2), ('CredentialChangeRequired', 3), ('CredentialChangeCompleted', 4), ('CredentialRecordAdded', 5), ('CredentialRecordRemoved', 6), ('CredentialRecordModified', 7), ('CredentialRecordAccessed', 8), ('CredentialAccessRequested', 9)]),
        ),
    ]
