# Generated by Django 4.2.2 on 2023-11-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CredentialVault', '0003_alter_notification_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='silenced_on',
        ),
        migrations.AlterField(
            model_name='notification',
            name='active_state',
            field=models.BooleanField(choices=[('active', 0), ('inactive', 1), ('silenced', 2)], default=True),
        ),
    ]
