# Generated by Django 4.2.2 on 2023-11-19 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CredentialVault', '0005_alter_notification_other_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='active_state',
            new_name='active',
        ),
    ]
