"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-469=ewrtbr4oaxg3-il^ueozd5&o3k3-608p9gw=7=k$7=-79q'

# Cryptographic variables - custom fernet implementation
FERNET = b'wYZlyHsW-Qyq_h_2nw8Vjv6Quhoe1sBECrgDfS6xI2E='.decode()
os.environ["SECRET"] = SECRET_KEY
os.environ["Fernet"] = FERNET

# change when implementing enviorment key
#from dotenv import load_dotenv, find_dotenv
#load_dotenv(find_dotenv())
#SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production! -Disable on production
DEBUG = False
ALLOWED_HOSTS = ["localhost", '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles', 
    # Custom Apps
    'UserManagement',
    'MessageBoard',
    'CredentialVault',
    'PasswordGenerator',
    'FriendFunctionality',
    # Community Apps
        #SSO functionality
    #email apps
    'sendgrid',
    #Cryptography
    "encrypted_fields",

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        
        # mysql - live enviorment
        # "ENGINE": "django.db.backends.mysql",
        #'NAME': 'TestServer',
        #'USER': 'Django-CredentialService',
        #'PASSWORD': 'jacksForLfE135@1',
        #'HOST':'localhost',
        #'PORT':'3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [ 
    str(BASE_DIR.joinpath('UserManagement/static/'),)
]
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'UserManagement.SolutionUser'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'


# PROFILE FUNCTIOANLITY
USER_PROFILE_MODEL = "UserManagement.SolutionUserProfile"
# Friend Functionality
USER_FRIEND_SYSTEM = "FriendFunctionality.FriendList"

#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

#Email verification Code
    #---------Active in production ------------#
    #store api key as env variable
SENDGRID_API_KEY = 	'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' #os.getenv('SENDGRID_API_KEY') 
EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_HOST_USER = 'apikey' # this is exactly the value 'apikey'
EMAIL_HOST_PASSWORD = SENDGRID_API_KEY
DEFAULT_FROM_EMAIL = 'jacobhenty2@gmail.com'

EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Cryptography module - Django Searchable Encrypted Fields
# generated using secrets.token_hex(32)
FIELD_ENCRYPTION_KEYS = [
    '65e7e5e65f96890ba3124e76336391c3edf91cf9409ade2b39b30b0d96678816'
]

# Project Security
## HTTPS -Strict Secure Mode 
#SECURE_HSTS_SECONDS = 3600
#SECURE_HSTS_PRELOAD = True
#SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT_ENABLED') != 'False'
##Sub Domain Security
#SECURE_HSTS_INCLUDE_SUBDOMAINS = True