# Generated by Django 4.2.2 on 2023-10-23 23:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=500)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('dislikes', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999999)])),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Empty Title', max_length=50)),
                ('body', models.TextField(max_length=500)),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
