# Generated by Django 4.2.2 on 2023-11-14 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionuserprofile',
            name='shared_key',
            field=models.CharField(max_length=128),
        ),
    ]
