# Generated by Django 4.2.2 on 2023-11-27 23:30

from django.db import migrations, models
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionuser',
            name='_key',
            field=encrypted_fields.fields.EncryptedCharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='solutionuserprofile',
            name='shared_key',
            field=models.CharField(default='', max_length=64),
        ),
    ]
