# Generated by Django 4.2.2 on 2023-08-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='activeState',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
