# Generated by Django 4.2.2 on 2023-10-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionuserprofile',
            name='shared_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
