# Generated by Django 4.2.2 on 2023-11-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_alter_solutionuserprofile_shared_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionuser',
            name='key',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
