# Generated by Django 4.2.2 on 2023-11-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0003_alter_solutionuser_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionuserprofile',
            name='shared_keys',
            field=models.TextField(blank=True, default=''),
        ),
    ]
